import { Project } from '@/types/project';

export const mockProjects: Project[] = [
  {
    id: "1",
    title: "Solo Leveling",
    coverImage: "https://images.unsplash.com/photo-1623275404659-51b5db8e4c67?w=800&q=80",
    description: "The story of the weakest hunter Sung Jin-Woo and his quest to become the strongest.",
    status: "ongoing",
    tags: ["Action", "Fantasy", "Adventure"],
    lastUpdated: "2024-01-15",
    chapters: 179,
    rating: 4.8,
    author: "Chugong",
    artist: "DUBU(REDICE STUDIO)",
    releaseYear: 2018,
    publisher: "D&C Media",
    genre: ["Action", "Fantasy", "Adventure"],
    language: "Korean",
    translationStatus: "completed",
    views: 15000000,
    likes: 980000,
    nextUpdateDate: "2024-02-01",
    averageChapterLength: 65,
    isLicensed: true,
    websiteUrl: "https://www.webtoons.com/en/action/solo-leveling/list?title_no=3793"
  },
  {
    id: "2",
    title: "Tower of God",
    coverImage: "https://images.unsplash.com/photo-1623275404659-51b5db8e4c67?w=800&q=80",
    description: "Follow Bam as he climbs the mysterious Tower in search of Rachel.",
    status: "ongoing",
    tags: ["Mystery", "Fantasy", "Drama"],
    lastUpdated: "2024-01-16",
    chapters: 550,
    rating: 4.7,
    author: "SIU",
    artist: "SIU",
    releaseYear: 2010,
    publisher: "Naver",
    genre: ["Mystery", "Fantasy", "Drama"],
    language: "Korean",
    translationStatus: "in-progress",
    views: 12000000,
    likes: 850000,
    nextUpdateDate: "2024-02-01",
    averageChapterLength: 80,
    isLicensed: true,
    websiteUrl: "https://www.webtoons.com/en/fantasy/tower-of-god/list?title_no=95"
  },
  {
    id: "3",
    title: "The Beginning After The End",
    coverImage: "https://images.unsplash.com/photo-1623275404659-51b5db8e4c67?w=800&q=80",
    description: "A king in his past life reborn into a world of magic and monsters.",
    status: "ongoing",
    tags: ["Reincarnation", "Fantasy", "Action"],
    lastUpdated: "2024-01-17",
    chapters: 175,
    rating: 4.6,
    author: "TurtleMe",
    artist: "Fuyuki23",
    releaseYear: 2018,
    publisher: "Tapas Media",
    genre: ["Reincarnation", "Fantasy", "Action"],
    language: "English",
    translationStatus: "completed",
    views: 8000000,
    likes: 620000,
    nextUpdateDate: "2024-02-01",
    averageChapterLength: 70,
    isLicensed: true,
    websiteUrl: "https://tapas.io/series/tbate-comic"
  }
];